# Generated by Django 5.2.4 on 2025-07-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='card',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='FeedbackResponse',
        ),
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
