# Generated by Django 5.2.4 on 2025-07-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
